galaxy_info:
  author: Yehonatan Devorkin
  description: This is a DEMO role - which should not make any system modifications
  company: Devorkin.net

  license: license (MIT)
  min_ansible_version: '2.1'

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []